"""
Tests for SwasthyaEHR v2.

Covers: model behaviour (auto-BMI, hospital id, lab auto-flag, catalog mapping),
serializer validation, RBAC on key endpoints, the OPD flow, and FHIR output
shape (so the exported JSON stays structurally valid for the HL7 validator).
"""

from datetime import date, timedelta

from django.contrib.auth import get_user_model
from django.utils import timezone
from rest_framework.test import APITestCase

from .constants import (
    Department,
    EncounterStatus,
    LabResultType,
    RegisteredBy,
    Role,
    StaffStatus,
)
from .fhir_serializers import (
    condition_to_fhir,
    encounter_to_fhir,
    observation_to_fhir,
    patient_to_fhir,
)
from .models import (
    Diagnosis,
    Encounter,
    LabOrder,
    LabReport,
    LabResult,
    Patient,
    Prescription,
    Vitals,
)

Staff = get_user_model()


def make_staff(email, role, department=None, password="pass12345"):
    u = Staff(
        email=email,
        full_name=email.split("@")[0].title(),
        role=role,
        department=department,
        status=StaffStatus.ACTIVE,
        is_active=True,
        must_change_password=False,
    )
    u.set_password(password)
    u.save()
    return u


def make_patient(nid="1234567890", **kw):
    defaults = dict(
        national_id=nid,
        first_name="Ram",
        last_name="Bahadur",
        phone_number="+977-9841000001",
        date_of_birth=date(1990, 1, 1),
        gender="male",
        blood_group="O+",
        allergies=["Penicillin"],
        registered_by=RegisteredBy.RECEPTIONIST,
    )
    defaults.update(kw)
    return Patient.objects.create(**defaults)


class ModelTests(APITestCase):
    def test_hospital_identifier_autogenerated(self):
        p = make_patient()
        self.assertTrue(p.hospital_identifier.startswith("HOSP-"))

    def test_national_id_unique(self):
        make_patient(nid="1111111111")
        with self.assertRaises(Exception):
            make_patient(nid="1111111111")

    def test_vitals_bmi_computed(self):
        recep = make_staff("r@x.np", Role.RECEPTIONIST)
        nurse = make_staff("n@x.np", Role.NURSE)
        p = make_patient()
        enc = Encounter.objects.create(
            patient=p, department=Department.ENDOCRINOLOGY, created_by=recep
        )
        v = Vitals.objects.create(
            encounter=enc, recorded_by=nurse, height_cm=170, weight_kg=72
        )
        # 72 / 1.7^2 = 24.9
        self.assertEqual(float(v.bmi), 24.9)

    def test_lab_result_autoflag_and_catalog(self):
        doctor = make_staff("d@x.np", Role.DOCTOR, Department.HEMATOLOGY)
        labtech = make_staff("l@x.np", Role.LAB_TECH)
        recep = make_staff("r2@x.np", Role.RECEPTIONIST)
        p = make_patient()
        enc = Encounter.objects.create(
            patient=p, department=Department.HEMATOLOGY, created_by=recep
        )
        order = LabOrder.objects.create(
            encounter=enc, patient=p, ordered_by=doctor, test_code="HEMOGLOBIN"
        )
        # catalog mapping populated test_name + loinc
        self.assertEqual(order.loinc_code, "718-7")
        report = LabReport.objects.create(
            lab_order=order, patient=p, entered_by=labtech
        )
        low = LabResult.objects.create(
            lab_report=report, patient=p, test_code="HEMOGLOBIN", result_value="8.00"
        )
        self.assertEqual(low.flag, "LOW")
        self.assertEqual(low.result_type, LabResultType.QUANTITATIVE)
        normal = LabResult.objects.create(
            lab_report=report, patient=p, test_code="HEMOGLOBIN", result_value="14.00"
        )
        self.assertEqual(normal.flag, "NORMAL")


class AuthTests(APITestCase):
    def test_login_by_email_returns_role(self):
        make_staff("doc@x.np", Role.DOCTOR, Department.CARDIOLOGY)
        resp = self.client.post(
            "/api/v1/auth/login/",
            {"email": "doc@x.np", "password": "pass12345"},
            format="json",
        )
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(resp.data["user"]["role"], Role.DOCTOR)

    def test_pending_staff_cannot_login(self):
        u = Staff(
            email="pending@x.np",
            full_name="Pending",
            role=Role.NURSE,
            status=StaffStatus.PENDING,
            is_active=False,
        )
        u.set_password("pass12345")
        u.save()
        resp = self.client.post(
            "/api/v1/auth/login/",
            {"email": "pending@x.np", "password": "pass12345"},
            format="json",
        )
        self.assertNotEqual(resp.status_code, 200)

    def test_staff_self_register_creates_pending(self):
        resp = self.client.post(
            "/api/v1/auth/register/",
            {
                "email": "newnurse@x.np",
                "full_name": "New Nurse",
                "role": Role.NURSE,
            },
            format="json",
        )
        self.assertEqual(resp.status_code, 201)
        u = Staff.objects.get(email="newnurse@x.np")
        self.assertEqual(u.status, StaffStatus.PENDING)
        self.assertFalse(u.is_active)


class RBACTests(APITestCase):
    def setUp(self):
        self.admin = make_staff("admin@x.np", Role.ADMIN)
        self.doctor = make_staff("doctor@x.np", Role.DOCTOR, Department.ENDOCRINOLOGY)
        self.recep = make_staff("recep@x.np", Role.RECEPTIONIST)

    def auth(self, user):
        resp = self.client.post(
            "/api/v1/auth/login/",
            {"email": user.email, "password": "pass12345"},
            format="json",
        )
        token = resp.data["access"]
        self.client.credentials(HTTP_AUTHORIZATION=f"Bearer {token}")

    def test_doctor_cannot_manage_staff(self):
        self.auth(self.doctor)
        resp = self.client.get("/api/v1/auth/staff/")
        self.assertEqual(resp.status_code, 403)

    def test_admin_can_list_staff(self):
        self.auth(self.admin)
        resp = self.client.get("/api/v1/auth/staff/")
        self.assertEqual(resp.status_code, 200)

    def test_receptionist_creates_encounter(self):
        self.auth(self.recep)
        p = make_patient()
        resp = self.client.post(
            "/api/v1/encounters/",
            {"patient": str(p.id), "department": Department.ENDOCRINOLOGY},
            format="json",
        )
        self.assertEqual(resp.status_code, 201)
        self.assertEqual(resp.data["status"], EncounterStatus.REGISTERED)


class FHIRShapeTests(APITestCase):
    def setUp(self):
        self.recep = make_staff("r@x.np", Role.RECEPTIONIST)
        self.doctor = make_staff("d@x.np", Role.DOCTOR, Department.ENDOCRINOLOGY)
        self.labtech = make_staff("l@x.np", Role.LAB_TECH)
        self.patient = make_patient()
        self.enc = Encounter.objects.create(
            patient=self.patient,
            department=Department.ENDOCRINOLOGY,
            created_by=self.recep,
        )

    def test_patient_fhir_shape(self):
        res = patient_to_fhir(self.patient)
        self.assertEqual(res["resourceType"], "Patient")
        self.assertEqual(res["gender"], "male")
        self.assertTrue(any(i["value"] == self.patient.national_id for i in res["identifier"]))

    def test_encounter_fhir_shape(self):
        res = encounter_to_fhir(self.enc)
        self.assertEqual(res["resourceType"], "Encounter")
        self.assertIn("class", res)
        self.assertIn("subject", res)

    def test_observation_quantitative_shape(self):
        order = LabOrder.objects.create(
            encounter=self.enc, patient=self.patient, ordered_by=self.doctor,
            test_code="FBS",
        )
        report = LabReport.objects.create(
            lab_order=order, patient=self.patient, entered_by=self.labtech
        )
        result = LabResult.objects.create(
            lab_report=report, patient=self.patient, test_code="FBS",
            result_value="120.00",
        )
        res = observation_to_fhir(result)
        self.assertEqual(res["resourceType"], "Observation")
        self.assertEqual(res["status"], "final")
        self.assertIn("valueQuantity", res)
        self.assertEqual(res["valueQuantity"]["value"], 120.0)

    def test_condition_fhir_shape(self):
        dx = Diagnosis.objects.create(
            encounter=self.enc, patient=self.patient, diagnosed_by=self.doctor,
            icd10_code="E11.9",
        )
        res = condition_to_fhir(dx)
        self.assertEqual(res["resourceType"], "Condition")
        self.assertEqual(res["code"]["coding"][0]["code"], "E11.9")


class SharingTests(APITestCase):
    def setUp(self):
        self.patient_user = make_staff("pat@x.np", Role.PATIENT)
        self.patient = make_patient(nid="9998887770")
        self.patient.user = self.patient_user
        self.patient.save()

    def test_share_request_then_approve_returns_bundle(self):
        # External hospital requests by NID (public).
        resp = self.client.post(
            "/api/v1/share/request/",
            {"national_id": "9998887770", "requester_label": "Hospital B"},
            format="json",
        )
        self.assertEqual(resp.status_code, 202)
        req_id = resp.data["request_id"]

        # Patient approves.
        login = self.client.post(
            "/api/v1/auth/login/",
            {"email": "pat@x.np", "password": "pass12345"},
            format="json",
        )
        self.client.credentials(HTTP_AUTHORIZATION=f"Bearer {login.data['access']}")
        dec = self.client.post(
            f"/api/v1/portal/share-requests/{req_id}/decision/",
            {"decision": "APPROVE"},
            format="json",
        )
        self.assertEqual(dec.status_code, 200)

        # External hospital polls -> gets the FHIR Bundle.
        self.client.credentials()  # drop auth (external)
        poll = self.client.get(f"/api/v1/share/request/{req_id}/")
        self.assertEqual(poll.status_code, 200)
        self.assertEqual(poll.data["resourceType"], "Bundle")
