# Generated by Django 5.2.16 on 2026-07-20 19:51

import core.models
import django.contrib.auth.validators
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'System Administrator'), ('RECEPTIONIST', 'Receptionist'), ('NURSE', 'Nurse'), ('DOCTOR', 'Doctor'), ('LAB_TECH', 'Laboratory Technician'), ('PHARMACIST', 'Pharmacist'), ('PATIENT', 'Patient')], max_length=20)),
                ('department', models.CharField(blank=True, choices=[('ENDOCRINOLOGY', 'Diabetes & Endocrinology'), ('INTERNAL_MEDICINE', 'Internal Medicine'), ('NEPHROLOGY', 'Nephrology'), ('CARDIOLOGY', 'Cardiology'), ('GASTROENTEROLOGY', 'Gastroenterology / Hepatobiliary'), ('INFECTIOUS_DISEASES', 'Infectious Diseases'), ('HEMATOLOGY', 'Hematology')], max_length=30, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending approval'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('must_change_password', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'core_staff',
            },
            managers=[
                ('objects', core.models.StaffManager()),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(choices=[('ENDOCRINOLOGY', 'Diabetes & Endocrinology'), ('INTERNAL_MEDICINE', 'Internal Medicine'), ('NEPHROLOGY', 'Nephrology'), ('CARDIOLOGY', 'Cardiology'), ('GASTROENTEROLOGY', 'Gastroenterology / Hepatobiliary'), ('INFECTIOUS_DISEASES', 'Infectious Diseases'), ('HEMATOLOGY', 'Hematology')], max_length=30)),
                ('visit_type', models.CharField(choices=[('NEW', 'New visit'), ('FOLLOWUP', 'Follow-up')], default='NEW', max_length=10)),
                ('chief_complaint', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('VITALS_DONE', 'Vitals recorded'), ('WITH_DOCTOR', 'With doctor'), ('LAB_PENDING', 'Awaiting lab'), ('LAB_DONE', 'Lab complete'), ('CLOSED', 'Closed')], default='REGISTERED', max_length=20)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('attending_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attending_encounters', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_encounters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_encounter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_code', models.CharField(max_length=50)),
                ('test_name', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(blank=True, choices=[('BIOCHEMISTRY', 'Biochemistry'), ('HEMATOLOGY', 'Hematology'), ('URINALYSIS', 'Urinalysis'), ('MICROBIOLOGY', 'Microbiology'), ('SEROLOGY', 'Serology / Immunology'), ('COAGULATION', 'Coagulation'), ('BLOOD_BANK', 'Blood Bank')], max_length=20)),
                ('loinc_code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent')], default='ROUTINE', max_length=10)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='core.encounter')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordered_lab_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_laborder',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual entry'), ('PDF_EXTRACTED', 'Extracted from PDF')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('EXTRACTED', 'Extracted'), ('CONFIRMED', 'Confirmed')], default='CONFIRMED', max_length=20)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entered_reports', to=settings.AUTH_USER_MODEL)),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.laborder')),
            ],
            options={
                'db_table': 'core_labreport',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital_identifier', models.CharField(editable=False, max_length=20, unique=True)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A positive'), ('A-', 'A negative'), ('B+', 'B positive'), ('B-', 'B negative'), ('AB+', 'AB positive'), ('AB-', 'AB negative'), ('O+', 'O positive'), ('O-', 'O negative'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('OTHER', 'Other')], max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('registered_by', models.CharField(choices=[('SELF', 'Self (public form)'), ('RECEPTIONIST', 'Receptionist')], max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_patient',
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_code', models.CharField(max_length=50)),
                ('test_name', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(blank=True, choices=[('BIOCHEMISTRY', 'Biochemistry'), ('HEMATOLOGY', 'Hematology'), ('URINALYSIS', 'Urinalysis'), ('MICROBIOLOGY', 'Microbiology'), ('SEROLOGY', 'Serology / Immunology'), ('COAGULATION', 'Coagulation'), ('BLOOD_BANK', 'Blood Bank')], max_length=20)),
                ('result_type', models.CharField(choices=[('QUANTITATIVE', 'Quantitative (numeric)'), ('REPORT', 'Report / Qualitative')], max_length=20)),
                ('loinc_code', models.CharField(blank=True, max_length=20)),
                ('result_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('result_unit', models.CharField(blank=True, max_length=20)),
                ('reference_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flag', models.CharField(blank=True, choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High')], max_length=10)),
                ('report_text', models.CharField(blank=True, max_length=1000)),
                ('lab_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.labreport')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='core.patient')),
            ],
            options={
                'db_table': 'core_labresult',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='labreport',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='core.patient'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='core.patient'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='core.patient'),
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icd10_code', models.CharField(choices=[('E11.9', 'E11.9 — Type 2 diabetes mellitus'), ('E10.9', 'E10.9 — Type 1 diabetes mellitus'), ('O24.4', 'O24.4 — Gestational diabetes mellitus'), ('R73.0', 'R73.0 — Prediabetes / impaired fasting glucose'), ('E03.9', 'E03.9 — Hypothyroidism, unspecified'), ('E05.9', 'E05.9 — Hyperthyroidism, unspecified'), ('M81.0', 'M81.0 — Osteoporosis'), ('I10', 'I10 — Essential (primary) hypertension'), ('J18.9', 'J18.9 — Pneumonia, unspecified'), ('J45.9', 'J45.9 — Asthma'), ('A90', 'A90 — Dengue fever'), ('A01.0', 'A01.0 — Typhoid fever'), ('R50.9', 'R50.9 — Fever, unspecified'), ('N18.9', 'N18.9 — Chronic kidney disease, unspecified'), ('N17.9', 'N17.9 — Acute kidney injury'), ('N20.0', 'N20.0 — Kidney stone (calculus)'), ('N04.9', 'N04.9 — Nephrotic syndrome'), ('N39.0', 'N39.0 — Urinary tract infection'), ('I21.9', 'I21.9 — Acute myocardial infarction'), ('I50.9', 'I50.9 — Heart failure, unspecified'), ('I25.1', 'I25.1 — Atherosclerotic heart disease'), ('I49.9', 'I49.9 — Cardiac arrhythmia, unspecified'), ('E78.5', 'E78.5 — Hyperlipidaemia / dyslipidemia'), ('B16.9', 'B16.9 — Acute hepatitis B'), ('B18.2', 'B18.2 — Chronic hepatitis C'), ('K74.6', 'K74.6 — Cirrhosis of liver'), ('K29.7', 'K29.7 — Gastritis, unspecified'), ('K85.9', 'K85.9 — Acute pancreatitis'), ('K80.2', 'K80.2 — Gallstone (calculus of gallbladder)'), ('K76.0', 'K76.0 — Fatty liver (non-alcoholic)'), ('A15.9', 'A15.9 — Respiratory tuberculosis'), ('U07.1', 'U07.1 — COVID-19'), ('B54', 'B54 — Malaria, unspecified'), ('B20', 'B20 — HIV disease'), ('A41.9', 'A41.9 — Sepsis, unspecified'), ('D64.9', 'D64.9 — Anaemia, unspecified'), ('D50.9', 'D50.9 — Iron deficiency anaemia'), ('C95.9', 'C95.9 — Leukaemia, unspecified'), ('C85.9', 'C85.9 — Non-Hodgkin lymphoma'), ('D68.9', 'D68.9 — Coagulation / bleeding disorder')], max_length=10)),
                ('disease_name', models.CharField(blank=True, max_length=255)),
                ('clinical_status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=20)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('diagnosed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_diagnoses', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='core.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='core.patient')),
            ],
            options={
                'db_table': 'core_diagnosis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('national_id', models.CharField(max_length=20)),
                ('requester_label', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'Pending patient approval'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='core.patient')),
            ],
            options={
                'db_table': 'core_accessrequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage_instruction', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.encounter')),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfilled_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.patient')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='written_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_prescription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('systolic_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('pulse', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('spo2', models.PositiveIntegerField(blank=True, null=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='core.encounter')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_vitals',
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=django.contrib.postgres.indexes.GinIndex(fields=['allergies'], name='patient_allergies_gin'),
        ),
    ]
