# Generated by Django 5.2.16 on 2026-07-23 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_share_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='requester_hospital',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='scope',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ExternalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('national_id', models.CharField(max_length=20)),
                ('source_hospital_code', models.CharField(max_length=20)),
                ('source_hospital_name', models.CharField(blank=True, max_length=120)),
                ('scope', models.JSONField(blank=True, default=list)),
                ('bundle', models.JSONField()),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imported_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_records', to='core.patient')),
            ],
            options={
                'db_table': 'core_external_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundShareRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('peer_code', models.CharField(max_length=20)),
                ('peer_name', models.CharField(blank=True, max_length=120)),
                ('peer_base_url', models.CharField(max_length=255)),
                ('national_id', models.CharField(max_length=20)),
                ('scope', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('peer_request_id', models.CharField(blank=True, max_length=64)),
                ('bundle', models.JSONField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('imported', models.BooleanField(default=False)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_share_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_outbound_share_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
