# Generated by Django 5.2.16 on 2026-07-13 10:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icd10_code', models.CharField(choices=[('A01.0', 'A01.0 — Typhoid fever'), ('A09', 'A09 — Acute gastroenteritis / diarrhoea'), ('A15.9', 'A15.9 — Respiratory tuberculosis'), ('A90', 'A90 — Dengue fever'), ('B50.9', 'B50.9 — Plasmodium falciparum malaria'), ('B54', 'B54 — Malaria, unspecified'), ('B19.9', 'B19.9 — Viral hepatitis, unspecified'), ('J00', 'J00 — Acute nasopharyngitis (common cold)'), ('J02.9', 'J02.9 — Acute pharyngitis'), ('J03.9', 'J03.9 — Acute tonsillitis'), ('J06.9', 'J06.9 — Acute upper respiratory infection'), ('J18.9', 'J18.9 — Pneumonia, unspecified'), ('N39.0', 'N39.0 — Urinary tract infection'), ('E11.9', 'E11.9 — Type 2 diabetes mellitus'), ('E10.9', 'E10.9 — Type 1 diabetes mellitus'), ('I10', 'I10 — Essential (primary) hypertension'), ('I25.1', 'I25.1 — Atherosclerotic heart disease'), ('I50.9', 'I50.9 — Heart failure, unspecified'), ('J44.9', 'J44.9 — Chronic obstructive pulmonary disease (COPD)'), ('J45.9', 'J45.9 — Asthma'), ('E78.5', 'E78.5 — Hyperlipidaemia, unspecified'), ('E03.9', 'E03.9 — Hypothyroidism, unspecified'), ('E05.9', 'E05.9 — Hyperthyroidism, unspecified'), ('N18.9', 'N18.9 — Chronic kidney disease, unspecified'), ('K21.9', 'K21.9 — Gastro-oesophageal reflux disease (GERD)'), ('K29.7', 'K29.7 — Gastritis, unspecified'), ('K76.0', 'K76.0 — Fatty liver (non-alcoholic)'), ('D50.9', 'D50.9 — Iron deficiency anaemia'), ('D64.9', 'D64.9 — Anaemia, unspecified'), ('E66.9', 'E66.9 — Obesity, unspecified'), ('E43', 'E43 — Severe protein-energy malnutrition'), ('M54.5', 'M54.5 — Low back pain'), ('M17.9', 'M17.9 — Osteoarthritis of knee'), ('G43.9', 'G43.9 — Migraine, unspecified'), ('R51', 'R51 — Headache'), ('F32.9', 'F32.9 — Depressive episode, unspecified'), ('F41.9', 'F41.9 — Anxiety disorder, unspecified'), ('R50.9', 'R50.9 — Fever, unspecified'), ('R05', 'R05 — Cough'), ('R10.4', 'R10.4 — Abdominal pain, unspecified'), ('A08.4', 'A08.4 — Viral intestinal infection (viral fever)'), ('T78.4', 'T78.4 — Allergy, unspecified')], max_length=10)),
                ('disease_name', models.CharField(blank=True, max_length=255)),
                ('clinical_status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=20)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('diagnosed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_diagnoses', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='core.patient')),
            ],
            options={
                'db_table': 'core_diagnosis',
                'ordering': ['-created_at'],
            },
        ),
    ]
